services:
  web:
    build: .
    restart: always
    command: gunicorn agrotrack.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DATABASE_URL: ${DATABASE_URL}
