# Generated by Django 5.0.11 on 2025-03-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='TRATAMIENTO PRUEBA', max_length=100),
            preserve_default=False,
        ),
    ]
