# Generated by Django 5.0.11 on 2025-03-08 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='expected_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='finish_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
