# Generated by Django 5.0.11 on 2025-03-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_rename_date_task_expected_date_remove_task_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='expected_date',
            new_name='date',
        ),
    ]
