# Generated by Django 5.0.11 on 2025-03-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_rename_expected_date_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
