# Generated by Django 5.0.11 on 2025-03-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_alter_task_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('spraying', 'Pulverización'), ('fertigation', 'Fertirrigación'), ('pest_control', 'Fumigación'), ('nutrition', 'Nutrición')], max_length=20),
        ),
    ]
