# Generated by Django 5.0.11 on 2025-03-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_task_water_per_ha_taskproduct_total_dose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskproduct',
            name='total_dose',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskproduct',
            name='total_dose_unit',
            field=models.CharField(choices=[('L', 'Litros'), ('kg', 'Kilogramos')], default='L', max_length=10),
            preserve_default=False,
        ),
    ]
