# Generated by Django 5.0.11 on 2025-03-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_alter_taskproduct_total_dose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dose_type',
            field=models.CharField(choices=[('kg_per_1000l', 'kg/1000L agua'), ('l_per_1000l', 'L/1000L agua'), ('kg_per_ha', 'kg/ha'), ('l_per_ha', 'L/ha'), ('pct', '%')], max_length=20),
        ),
        migrations.AlterField(
            model_name='taskproduct',
            name='dose_type',
            field=models.CharField(choices=[('kg_per_1000l', 'kg/1000L agua'), ('l_per_1000l', 'L/1000L agua'), ('kg_per_ha', 'kg/ha'), ('l_per_ha', 'L/ha'), ('pct', '%')], max_length=20),
        ),
    ]
