# Generated by Django 5.0.11 on 2025-03-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_alter_product_dose_type_alter_taskproduct_dose_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
